title: Hamono's webpackage
author: Hamono
email: your-email@domain.com
description: > # this is good
  My first webpage

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
